name: Build & Push Prod
on:
  push:
    branches:
        - main
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build images
      run: |
        docker build -t api -f api/Dockerfile-api .
    - name: Tag images
      run: | 
        docker tag api ghcr.io/fixterjake/api:latest
    - name: Push images
      run: |
        docker push ghcr.io/fixterjake/api:latest