name: Build & Push Prod
on:
  push:
    branches:
      - main
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
    - name: Inject server secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: "./Server/appsettings.json"
      env:
        ConnectionString: ${{ secrets.CONN_STRING_PROD }}
        SpacesKey: ${{ secrets.DO_SPACES_KEY }}
        SpacesSecret: ${{ secrets.DO_SPACES_Secret }}
        VatsimServerOptions.JwtBearerConfig.Secret: ${{ secrets.JWT_PROD_SECRET }}
        VatsimServerOptions.JwtBearerConfig.Issuer: ${{ secrets.JWT_PROD_ISS }}
        VatsimServerOptions.JwtBearerConfig.Audience: ${{ secrets.JWT_PROD_AUD }}
        VatsimServerOptions.VatsimTokenRequestOptions.ClientId: ${{ secrets.VATSIM_PROD_CLIENT_ID }}
        VatsimServerOptions.VatsimTokenRequestOptions.ClientSecret: ${{ secrets.VATSIM_PROD_CLIENT_SECRET }}
        VatsimServerOptions.VatsimTokenRequestOptions.RedirectUri: ${{ secrets.VATSIM_PROD_REDIRECT_URI }}
        EmailOptions.Username: ${{ secrets.EMAIL_USERNAME }}
        EmailOptions.Password: ${{ secrets.EMAIL_PASSWORD }}
        EmailOptions.From: ${{ secrets.EMAIL_FROM_PROD }}
        EmailOptions.Website: ${{ secrets.EMAIL_WEBSITE_PROD }}
        Sentry.Dsn: ${{ secrets.SENTRY_DSN_SERVER }}
        Redis.Host: ${{ secrets.REDIS_HOST }}
    - name: Inject jobs secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: "./Jobs/appsettings.json"
      env:
        ConnectionString: ${{ secrets.CONN_STRING_PROD }}
        VatusaApiKey: ${{ secrets.VATUSA_API_KEY }}
        SentryDsn: ${{ secrets.SENTRY_DSN_JOBS }}
    - name: Log into registry
      run: docker login -u ${{ secrets.DO_REGISTRY_TOKEN }} -p ${{ secrets.DO_REGISTRY_TOKEN }} registry.digitalocean.com
    - name: Build server image 
      run: docker build -t server -f Server/Dockerfile .
    - name: Build jobs image 
      run: docker build -t jobs -f Jobs/Dockerfile .
    - name: Tag server image
      run: docker tag server registry.digitalocean.com/vzdc-artcc/server:latest
    - name: Tag jobs image
      run: docker tag jobs registry.digitalocean.com/vzdc-artcc/jobs:latest
    - name: Push server image
      run: docker push registry.digitalocean.com/vzdc-artcc/server:latest
    - name: Push jobs image
      run: docker push registry.digitalocean.com/vzdc-artcc/jobs:latest