name: Build
on:
  pull_request:
    types: [opened, reopened]
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
    - name: Build images
      run: |
        docker build -t api -f ./api/ARTCC.Core.API/Dockerfile .