name: Build & Push Dev
on:
  push:
    branches:
        - develop
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
    - name: Inject server secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: "./Server/appsettings.json"
      env:
        ConnectionString: ${{ secrets.CONN_STRING_DEV }}
        SpacesKey: ${{ secrets.DO_SPACES_KEY }}
        SpacesSecret: ${{ secrets.DO_SPACES_Secret }}
        VatsimServerOptions.JwtBearerConfig.Secret: ${{ secrets.JWT_DEV_SECRET }}
        VatsimServerOptions.JwtBearerConfig.Issuer: ${{ secrets.JWT_DEV_ISS }}
        VatsimServerOptions.JwtBearerConfig.Audience: ${{ secrets.JWT_DEV_AUD }}
        VatsimServerOptions.VatsimTokenRequestOptions.ClientId: ${{ secrets.VATSIM_DEV_CLIENT_ID }}
        VatsimServerOptions.VatsimTokenRequestOptions.ClientSecret: ${{ secrets.VATSIM_DEV_CLIENT_SECRET }}
        VatsimServerOptions.VatsimTokenRequestOptions.RedirectUri: ${{ secrets.VATSIM_DEV_REDIRECT_URI }}
        EmailOptions.Username: ${{ secrets.EMAIL_USERNAME }}
        EmailOptions.Password: ${{ secrets.EMAIL_PASSWORD }}
        EmailOptions.From: ${{ secrets.EMAIL_FROM_DEV }}
        EmailOptions.Website: ${{ secrets.EMAIL_WEBSITE_DEV }}
        Sentry.Dsn: ${{ secrets.SENTRY_DSN_SERVER }}
        Redis.Host: ${{ secrets.REDIS_HOST_DEV }}
    - name: Inject jobs secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: "./Jobs/appsettings.json"
      env:
        ConnectionString: ${{ secrets.CONN_STRING_DEV }}
        AvwxApiKey: ${{ secrets.AVWX_API_KEY }}
        VatusaApiKey: ${{ secrets.VATUSA_API_KEY }}
        SentryDsn: ${{ secrets.SENTRY_DSN_JOBS }}
    - name: Log into registry
      run: docker login -u ${{ secrets.DO_REGISTRY_TOKEN }} -p ${{ secrets.DO_REGISTRY_TOKEN }} registry.digitalocean.com
    - name: Build server image 
      run: docker build -t server -f Server/Dockerfile .
    - name: Build jobs image 
      run: docker build -t jobs -f Jobs/Dockerfile .
    - name: Tag server image
      run: docker tag server registry.digitalocean.com/vzdc/server:dev
    - name: Tag jobs image
      run: docker tag jobs registry.digitalocean.com/vzdc/jobs:dev
    - name: Push server image
      run: docker push registry.digitalocean.com/vzdc/server:dev
    - name: Push jobs image
      run: docker push registry.digitalocean.com/vzdc/jobs:dev
    - uses: actions/checkout@v2
    - name: Create Server Release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: vzdc
        SENTRY_PROJECT: server
      with:
        environment: development
    - name: Create Jobs Release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: vzdc
        SENTRY_PROJECT: jobs
      with:
        environment: development