name: Build & Push Prod
on:
  push:
    branches:
        - main
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build api images
      run: |
        cd api
        docker build -t artcc-api -f ARTCC.Core.API/Dockerfile .
        docker build -t artcc-jobs-roster -f ARTCC.Core.Jobs.Roster/Dockerfile .
    - name: Build ui image
      run: |
        cd ui
        docker build -t artcc-ui .
    - name: Tag images
      run: | 
        docker tag artcc-api ghcr.io/fixterjake/artcc-api:latest
        docker tag artcc-jobs-roster ghcr.io/fixterjake/artcc-jobs-roster:latest
        docker tag artcc-ui ghcr.io/fixterjake/artcc-ui:latest
    - name: Push images
      run: |
        docker push ghcr.io/fixterjake/artcc-api:latest
        docker push ghcr.io/fixterjake/artcc-jobs-roster:latest
        docker push ghcr.io/fixterjake/artcc-ui:latest
    - name: Restart api
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: -n artcc-prod rollout restart api-prod
    - name: Restart ui
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: -n artcc-prod rollout restart ui-prod